name: isolate_bidirecional
description: Comunicação bidirecional em isolates pelo stream_channel.
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  stream_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  climatempo: climatempo