name: extensions
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
