name: climatempo
description: Aplicação CLI para consulta de clima.
version: 0.0.1

environment:
  sdk: ^3.5.1

dependencies:
  args: ^2.4.2
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  
executables:
  climatempo: climatempo